apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ensek-energy
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'alexandercthomp/backstage-demo'
spec:
  type: website
  lifecycle: production
  owner: user:alexandercthomp
